explore/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from main.views import TemplateView
from django.views.generic.base import RedirectView
admin.site.site_header = "JustRokket Admin"
from main import views
from . import settings


urlpatterns = [
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^explore-post/$', views.ExplorePost.as_view(), name='explore-post'),
    url(r'^profile/(?P<pk>\d+)', views.UpdateProfile.as_view(), name='profile'),
    url(r'^selected-college/(?P<pk>\d+)/$', views.Screen3.as_view(), name='selected-college'),
    url(r'^selection/$', views.Selection.as_view(), name='selected'),
    url(r'^finalize/(?P<pk>\d+)$', views.profile_view, name='finalized'),
    url(r'^explore/(?P<id>\d+)$', views.Explore.as_view(), name='explore'),
    url(r'^v/(?P<email>.*)', views.VerifyEmail.as_view(), name='v'),
    url(r'^vm/(?P<mobile>.*)', views.VerifyMobile.as_view(), name='vm'),
    url(r'^otp/(?P<otp>.*)/(?P<type>.*)', views.VerifyOTP.as_view(), name='otp'),
    url(r'^thank-you/(?P<pk>.*)', views.Screen6.as_view(), name='thank-you'),
    url(r'^refund/(?P<pk>.*)', views.RequestRefund.as_view(), name='refund-you'),
    # url(r'^blog/$', views.BlogView.as_view(), name='blog'),
    # url(r'^blog-details', views.BlogdetailsView.as_view(), name='blog-details'),
    url(r'^user-login', views.LoginUser.as_view(), name='login-user'),
    # url(r'^userlogin', views.UserLogin.as_view(), name='user-login'),
    url(r'^update-profile/(?P<pk>\d+)/', views.UpdateProfile.as_view(), name='update-profile'),
    url(r'^create-profile/', views.CreateProfile.as_view(), name='create-profile'),
    url(r'^populate/course/categories/', views.populate_course_categories, name='populate-course-categories'),
    url(r'^populate/qualification/exam/', views.populate_qualification_exam,
        name='populate-qualification-exam'),
    url(r'^populate/competitve/exam/', views.populate_competitve_exam,
        name='populate-competitve-exam'),
    url(r'^signup/', views.SignupView.as_view(), name='signup'),
    url(r'^about-us/', views.AboutView.as_view(), name='about-us'),
    url(r'^contact-us/', views.ContactView.as_view(), name='contact-us'),
    url(r'^partner-institutions/', views.PartnersView.as_view(), name='partners'),
    url(r'^faq/', views.FaqView.as_view(), name='faq'),
    url(r'^privacy-policy/', views.PrivacyView.as_view(), name='privacy'),
    url(r'^tnc/', views.TermsView.as_view(), name='terms-of-use'),
    url(r'^refund-policy/', views.RefundAssuranceView.as_view(), name='refund-assurance'),
    url(r'^why-students-can-depend-on-us/', views.WhyDependView.as_view(), name='why-you-can-depend-on-us'),
    url(r'^how-just-rokket-helps-partner-institutions/', views.WorkView.as_view(), name='how-just-rokket-helps-you'),
    url(r'^how-this-works/', views.HowView.as_view(), name='how-this-works'),
    url(r'^pricing/', views.PricingView.as_view(), name='pricing'),
    url(r'^forgot-password/$', views.ForgotPassword.as_view(), name='forgot-password'),
    url(r'^forgot-password/verify-otp/(?P<otp>.*)$', views.ForgotPasswordVerifyOTP.as_view(), name='forgot-password'),
    url(r'^forgot-password/new-password/(?P<otp>.*)', views.ForgotPasswordNewPassword.as_view(), name='forgot-password'),
    url(r'^reset-password-profile-page', views.ResetPasswordProfilePage.as_view(), name='forgot-password'),
    url(r'^contact-form', views.ContactForm.as_view(), name='contact-form'),
    # payment
    url(r'^how-just-rokket-helps-you/', views.WorkView.as_view(), name='how-just-rokket-helps-you'),
    # url(r'^payment/(?P<pk>\d+)/', views.payment_processor, name='payment-processor'),
    url(r'^payment/redirect/', views.redirectview, name='how-this-works'),
    url(r'^payment/cancel/', views.cancelview, name='cancel'),
    url(r'^accounts/facebook/login/callback/(?P<token>.*)', views.LoginUser.as_view(), name='login-user'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^newsletter/$', views.Newsletter.as_view(), name='newsletter'),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^sitemap\.xml$', TemplateView.as_view(template_name='sitemap.xml', content_type='text/xml')),

    url(r'^apple-touch-icon\.png$', RedirectView.as_view(url="/static/apple-touch-icon.png", permanent=False)),
    url(r'^favicon-32x32\.png$', RedirectView.as_view(url="/static/favicon-32x32.png", permanent=False)),
    url(r'^favicon-16x16\.png$', RedirectView.as_view(url="/static/favicon-16x16.png", permanent=False)),
    url(r'^favicon\.ico$', RedirectView.as_view(url="/static/favicon.ico", permanent=False)),
    url(r'^manifest\.json$', RedirectView.as_view(url="/static/manifest.json", permanent=False)),
    url(r'^safari-pinned-tab\.svg$', RedirectView.as_view(url="/static/safari-pinned-tab.svg", permanent=False)),
    url(r'^featured-image\.jpg$', RedirectView.as_view(url="/static/images/featured.jpg")),
    url(r'^qa/', include('qa.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qa/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.QuestionIndexView.as_view(), name='qa_index'),

    url(r'^question/(?P<pk>\d+)/$',
        views.QuestionDetailView.as_view(), name='qa_detail'),

    url(r'^question/(?P<pk>\d+)/(?P<slug>[-_\w]+)/$',
        views.QuestionDetailView.as_view(), name='qa_detail'),

    url(r'^question/answer/(?P<answer_id>\d+)/$',
        views.AnswerQuestionView.as_view(), name='qa_answer_question'),

    url(r'^question/close/(?P<question_id>\d+)/$',
        views.CloseQuestionView.as_view(), name='qa_close_question'),

    url(r'^new-question/$', views.CreateQuestionView.as_view(),
        name='qa_create_question'),

    url(r'^edit-question/(?P<question_id>\d+)/$',
        views.UpdateQuestionView.as_view(),
        name='qa_update_question'),

    url(r'^answer/(?P<question_id>\d+)/$',
        views.CreateAnswerView.as_view(), name='qa_create_answer'),

    url(r'^answer/edit/(?P<answer_id>\d+)/$',
        views.UpdateAnswerView.as_view(), name='qa_update_answer'),

    url(r'^vote/question/(?P<object_id>\d+)/$',
        views.QuestionVoteView.as_view(), name='qa_question_vote'),

    url(r'^vote/answer/(?P<object_id>\d+)/$',
        views.AnswerVoteView.as_view(), name='qa_answer_vote'),

    url(r'^comment-answer/(?P<answer_id>\d+)/$',
        views.CreateAnswerCommentView.as_view(),
        name='qa_create_answer_comment'),

    url(r'^comment-question/(?P<question_id>\d+)/$',
        views.CreateQuestionCommentView.as_view(),
        name='qa_create_question_comment'),

    url(r'^comment-question/edit/(?P<comment_id>\d+)/$',
        views.UpdateQuestionCommentView.as_view(),
        name='qa_update_question_comment'),

    url(r'^comment-answer/edit/(?P<comment_id>\d+)/$',
        views.UpdateAnswerCommentView.as_view(),
        name='qa_update_answer_comment'),

    url(r'^search/$', views.QuestionsSearchView.as_view(), name='qa_search'),

    url(r'^tag/(?P<tag>[-\w]+)/$',
        views.QuestionsByTagView.as_view(), name='qa_tag'),

    url(r'^tag/$',
        views.TagView.as_view(), name='tag'),

    url(r'^profile/(?P<user_id>\d+)/$', views.profile, name='qa_profile'),

    url('^markdown/', include('django_markdown.urls')),

    url(r'hitcount/', include('hitcount.urls', namespace='hitcount')),

]

qa/models.py
from annoying.fields import AutoOneToOneField
from django.conf import settings
from django.db import models
from django.db.models import F
from django.utils.text import slugify
from django_markdown.models import MarkdownField
from hitcount.models import HitCountMixin
# from taggit.managers import TaggableManager


from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType


class tag(models.Model):
	"""docstring for tag"""

	name = models.CharField(max_length=250)

	content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
	object_id = models.PositiveIntegerField()
	content_object = GenericForeignKey('content_type', 'object_id')

	def __str__(self):              # __unicode__ on Python 2
		return self.name



class UserQAProfile(models.Model):
    """Model class to define a User profile for the app, directly linked
    to the core Django user model."""
    user = AutoOneToOneField(settings.AUTH_USER_MODEL, primary_key=True)
    points = models.IntegerField(default=0)
    # The additional attributes we wish to include.
    website = models.URLField(blank=True)

    def modify_reputation(self, added_points):
        """Core function to modify the reputation of the user profile."""
        self.points = F('points') + added_points
        self.save()

    def __str__(self):  # pragma: no cover
        return self.user.username


class Question(models.Model, HitCountMixin):
    """Model class to contain every question in the forum"""
    slug = models.SlugField(max_length=200)
    title = models.CharField(max_length=200, blank=False)
    description = MarkdownField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    tag = models.ForeignKey(tag, default=1)
    reward = models.IntegerField(default=0)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    closed = models.BooleanField(default=False)
    positive_votes = models.IntegerField(default=0)
    negative_votes = models.IntegerField(default=0)
    total_points = models.IntegerField(default=0)
    approve = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
            try:
                points = settings.QA_SETTINGS['reputation']['CREATE_QUESTION']

            except KeyError:
                points = 0

            self.user.userqaprofile.modify_reputation(points)

        self.total_points = self.positive_votes - self.negative_votes
        super(Question, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class Answer(models.Model):
    """Model class to contain every answer in the forum and to link it
    to the proper question."""
    question = models.ForeignKey(Question)
    answer_text = MarkdownField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    updated = models.DateTimeField('date updated', auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    answer = models.BooleanField(default=False)
    positive_votes = models.IntegerField(default=0)
    negative_votes = models.IntegerField(default=0)
    total_points = models.IntegerField(default=0)
    approve = models.BooleanField(default=False)


    def save(self, *args, **kwargs):
        try:
            points = settings.QA_SETTINGS['reputation']['CREATE_ANSWER']

        except KeyError:
            points = 0

        self.user.userqaprofile.modify_reputation(points)
        self.total_points = self.positive_votes - self.negative_votes
        super(Answer, self).save(*args, **kwargs)

    def __str__(self):  # pragma: no cover
        return self.answer_text

    class Meta:
        ordering = ['-answer', '-pub_date']


class VoteParent(models.Model):
    """Abstract model to define the basic elements to every single vote."""
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    value = models.BooleanField(default=True)

    class Meta:
        abstract = True


class AnswerVote(VoteParent):
    """Model class to contain the votes for the answers."""
    answer = models.ForeignKey(Answer)

    class Meta:
        unique_together = (('user', 'answer'),)


class QuestionVote(VoteParent):
    """Model class to contain the votes for the questions."""
    question = models.ForeignKey(Question)

    class Meta:
        unique_together = (('user', 'question'),)


class BaseComment(models.Model):
    """Abstract model to define the basic elements to every single comment."""
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)

    class Meta:
        abstract = True

    def __str__(self):  # pragma: no cover
        return self.comment_text


class AnswerComment(BaseComment):
    """Model class to contain the comments for the answers."""
    comment_text = MarkdownField()
    answer = models.ForeignKey(Answer)

    def save(self, *args, **kwargs):
        try:
            points = settings.QA_SETTINGS['reputation']['CREATE_ANSWER_COMMENT']

        except KeyError:
            points = 0

        self.user.userqaprofile.modify_reputation(points)
        super(AnswerComment, self).save(*args, **kwargs)


class QuestionComment(BaseComment):
    """Model class to contain the comments for the questions."""
    comment_text = models.CharField(max_length=250)
    question = models.ForeignKey(Question)

    def save(self, *args, **kwargs):
        try:
            points = settings.QA_SETTINGS['reputation']['CREATE_QUESTION_COMMENT']

        except KeyError:
            points = 0

        self.user.userqaprofile.modify_reputation(points)
        super(QuestionComment, self).save(*args, **kwargs)






	 

qa/forms.py
from django import forms
from django.conf import settings
from qa.models import Question


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'description', 'tag']

    def __init__(self, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)

        try:
            settings.QA_SETTINGS['qa_description_optional']
            self.fields['description'].required = not settings.QA_SETTINGS[
                'qa_description_optional']

        except KeyError:
            pass

qa/templates/qa/base.html
{% load staticfiles %}
<div class="topbar"></div>
<div class="container">
<title>Simple QA</title>
<link rel="icon" type="image/png" href="static/qa/icon.ico">
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>


<link href='http://fonts.googleapis.com/css?family=Roboto:300' rel='stylesheet' type='text/css'>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="{% static 'css/qa.css' %}" rel="stylesheet"/>

<div class="page-header">
  <a class="btn btn-lg btn-warning pull-right" href="#search"><span class="glyphicon glyphicon-search" aria-hidden="true"></span> Find</a><a class="btn btn-lg btn-danger pull-right" href="{% url 'qa_create_question' %}"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Ask Question</a><h1><a href="{% url 'qa_index' %}"><img width="50px" src="http://icons.iconarchive.com/icons/seanau/flat-app/256/Questionmark-icon.png" /><orange>Simple QA</orange> </a><small>Open Questions</small></h1>
</div>
<div class="container">
{% if messages %}
  {% for message in messages %}
    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
  {% endfor %}
{% endif %}
{% block content %}

{% endblock content %}
 <div id="search">
   <button type="button" class="close">×</button>
   <form method="GET" action="{% url 'qa_search' %}">
     <input type="search" value="" name="word" placeholder="type keyword(s) here" />
     <input class="btn btn-lg btn-warning" type="submit" value="Find" />
   </form>
   
 </div>
</div>
<hr>
<center>
  <a href="http://www.djangoproject.com/"><img src="https://www.djangoproject.com/m/img/badges/djangoproject120x25.gif" border="0" alt="A Django project." title="A Django project." /></a> ·
  <a href="https://github.com/swappsco/django-qa/">Github</a> ·
  <a data-toggle="modal" data-target="#apiModal">API</a> ·
  <small><a href="/admin">Admin Panel</a></small></center>
 <br/><br/>


 <!-- Modal -->
 <div class="modal fade" id="apiModal" tabindex="-1" role="dialog" aria-labelledby="APIModal" aria-hidden="true">
   <div class="modal-dialog">
     <div class="modal-content">
       <div class="modal-header">
         <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
         <h4 class="modal-title" id="myModalLabel"><span class="glyphicon glyphicon-cloud" aria-hidden="true"></span> API Access</h4>
       </div>
       <div class="modal-body">
         <ul>
           <li>
             <b>List of Questions</b>
             <br/>Retrieve the list of questions.
             <br/>json URL : <code class="custom-code">http://djangoqa.azurewebsites.net/api/questions/?format=json</code>
           </li>
           <br/>
           <li>
             <b>List of Users</b>
             <br/>Retrieve the list of users.
             <br/>json URL : <code class="custom-code">http://djangoqa.azurewebsites.net/api/users/?format=json</code>
           </li>
          </ul>
       </div>
       <div class="modal-footer">
         <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
       </div>
     </div>
   </div>
 </div>
</div>

{% block js %}
<script>
$(function () {
  $('a[href="#search"]').on('click', function(event) {
    event.preventDefault();
    $('#search').addClass('open');
    $('#search > form > input[type="search"]').focus();
  });

  $('#search, #search button.close').on('click keyup', function(event) {
    if (event.target == this || event.target.className == 'close' || event.keyCode == 27) {
      $(this).removeClass('open');
    }
  });

});
</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
{% endblock js %}
{%block extra_js %}{% endblock extra_js %}

qa/templates/qa/create_answer.html
{% extends 'qa/base.html' %}
{% load django_markdown %}

{% block content %}

  {% if message %}
  <strong>Enter a valid Question!</strong>
  {% endif %}

  <form method="post" action="{% block action_url %}{% url 'qa_create_answer' view.kwargs.question_id %}{% endblock action_url %}">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn pull-right btn-success" type="submit" value="Submit Answer" />
  </form>

</div>

{% endblock content %}

{% block extra_js %}
  {% markdown_editor "#id_answer_text" %}
  {% markdown_media %}
{% endblock %}

qa/templates/qa/create_comment.html
{% extends 'qa/base.html' %}
{% load django_markdown %}

{% block content %}

  {% if message %}
    <strong>Enter a valid Answer!</strong>
  {% endif %}

  <form method="post" action="">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn pull-right btn-success" type="submit" value="Submit Comment" />
  </form>

</div>

{% markdown_editor "#ans" %}
{% markdown_media %}
{% endblock content %}

qa/templates/qa/create_question.html
{% extends 'qa/base.html' %}
{% load django_markdown %}

{% block content %}

  {% if message %}
  <strong>Enter a valid Question!</strong>
  {% endif %}

  <form method="post" action="{% block action_url %}{% url 'qa_create_question' %}{% endblock action_url %}">
    {{ form.as_p }}
    {% csrf_token %}
    <input class="btn pull-right btn-success" type="submit" value="Submit Question" />
  </form>

</div>

{% endblock content %}

{% block extra_js %}
  {% markdown_editor "#id_description" %}
  {% markdown_media %}
{% endblock extra_js %}

qa/templates/qa/detail_question.html
{% extends 'qa/base.html' %}
{% load django_markdown %}
{% load staticfiles %}

{% block content %}

{% if question.closed %}
  <div class="closed"></div>
{% else %}
    {% if question.reward %}
    <div class="rewarding"></div>
    {% else %}
    <div class="open"></div>
    {% endif %}
{% endif %}


{% if message %}
    <div class="alert alert-danger" role="alert">{{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endif %}
{% comment %}

{% if question.reward %}
    <div class="alert alert-info" role="alert">This question has been marked to be worth a reward of <b>{{ question.reward }}<b> points!
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endif %}
{% endcomment %}

<div class="jumbotron">
  <div class="row">
    {% if user.is_authenticated and question.user != user %}
      <div class ="col-sm-1">
        <big class="pull-left custom-big"><b>{{ question.total_points }}</b></big>
      </div>
      <div class ="col-sm-1">
        <form action="{% url 'qa_question_vote' question.id %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="next" value="{{ request.path }}">
          <input type="hidden" name="upvote" value="on">
          <button type="submit" class="btn btn-sm btn-success" data-toggle="tooltip" data-placement="top" title="Vote Up this answer"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></button>
        </form>
          <form action="{% url 'qa_question_vote' question.id %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="next" value="{{ request.path }}">
          <button type="submit" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="bottom" title="Vote Down this answer"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span></button>
        </form>
      </div>
    {% endif %}
    <div class="col-sm-10">
      <small class="pull-right">Posted by {{ question.user.username }}, {{ question.pub_date }}</small>
      {% if user.is_authenticated and question.user == user %}<a href="{% url 'qa_update_question' question.id %}"><small class="pull-right">Edit &nbsp;</small></a>{% endif %}
      <h3><cool>Q: </cool>{{ question.title }}</h3>
      <h4>{{ question.description|markdown }}</h4>
      <p>
      {% if question.closed %}
          <p class="pull-right">This Question has been closed.</p>
      {% else %}
          <a class="btn btn-primary btn-sm pull-right" href="{% url 'qa_create_answer' question.id %}" role="button">Answer this Question!</a>
          <a class="btn btn-primary btn-sm pull-right" href="{% url 'qa_create_question_comment' question.id %}" role="button">comment this Question!</a>
      {% endif %}
      </p>
    </div>
  </div>
</div>
{% if last_comments %}
  <h4>comments</h4>
  {% for comment in last_comments %}
  <div class="row">
    <div class="col-md-9 col-md-offset-1">
    <p><b>{{ comment.comment_text|markdown }}</b><small>, <a href="{% url 'qa_profile' comment.user.id %}">{{ comment.user.username }}</a> <div class="pull-right">{{ comment.pub_date }}</div></small></p>{% if comment.user == user %}<a href="{% url 'qa_update_question_comment' comment.id %}" class="pull-right"><small>Edit &nbsp;</small></a>{% endif %}
    </div>
  </div>
  {% endfor %}
{% endif %}
{% if answers %}
  <h3>Answers</h3>
  <hr/>

    {% for answer in answers %}
    <div class="row">
      {% if user.is_authenticated and answer.user != user %}
      <div class ="col-md-1">
        <div class="row">
          <div class ="col-sm-1"><big class="pull-left custom-big"><b>{{ answer.total_points }}</b></big></div>
          <div class ="col-sm-1">
          <form action="{% url 'qa_answer_vote' answer.id %}" method="POST">
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ request.path }}">
              <input type="hidden" name="upvote" value="on">
              <button type="submit" class="btn btn-sm btn-success" data-toggle="tooltip" data-placement="top" title="Vote Up this answer"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></button>
          </form>
          <form action="{% url 'qa_answer_vote' answer.id %}" method="POST">
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ request.path }}">
              <button type="submit" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="bottom" title="Vote Down this answer"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span></button></div>
          </form>
        </div>
      </div>
      {% endif %}
      <div class ="col-md-9">
        <a href="{% url 'qa_create_answer_comment' answer.id %}" class="pull-right"><small><span class="glyphicon glyphicon-comment" aria-hidden="true"></span> Comment &nbsp;</small></a>
        {% if answer.user == user %}<a href="{% url 'qa_update_answer' answer.id %}" class="pull-right"><small>Edit &nbsp;</small></a>{% endif %}
            <div id="ans" class="alert alert-primary" role="alert">{{ answer.answer_text|markdown }}</div>
        {% if answer.answercomment_set %}
          {% for comment in answer.answercomment_set.all %}
            <p><b>{{ comment.comment_text|markdown }}</b><small>, <a href="{% url 'qa_profile' comment.user.id %}">{{ comment.user.username }}</a> <div class="pull-right">{{ comment.pub_date }}</div></small></p>{% if comment.user == user %}<a href="{% url 'qa_update_answer_comment' comment.id %}" class="pull-right"><small>Edit &nbsp;</small></a>{% endif %}
          <hr>
          {% endfor %}
        {% endif %}
      </div>
          <div class ="col-md-2">
            {% if answer.user.userqaprofile.picture %}
                <img class="pull-right" src="{{ answer.user.userqaprofile.picture }}">
            {% else %}
                <img class="pull-right" width="50px" height="50px" src="{% static "qa/user.png" %}">
            {% endif %}
            <p class="pull-right">- <b><a href="{% url 'qa_profile' answer.user.id %}">{{ answer.user.username }}</a> ({{ answer.user.userqaprofile.points }})</b></p>
                {% if user.is_authenticated and answer.question.user == user and answer.question.closed == False %}
                    <form action="{% url 'qa_close_question' question.id %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.path }}"/>
                        <button type="submit" class="btn btn-success btn-sm pull-right" data-toggle="tooltip" data-placement="bottom" title="Close this question"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></button></div>
                    </form>
                {% else %}
                    {% if  answer.answer == True %}
                        <button class="btn btn-success btn-sm pull-right" title="Picked Answer"><span class="glyphicon glyphicon-star" aria-hidden="true"></span></button></div>
                    {% endif %}
                {% endif %}
          </div>
    </div>
  <hr>
    {% endfor %}

{% else %}
<img class="pull-right" src="{% static "qa/question.jpg" %}" alt="question"/>
<center><h2>This question is still open, <a href="{% url 'qa_create_answer' question.id %}" role="button">Write answer!</a></h2></center>
{% endif %}


{% endblock content %}
{% block extra_js %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>
{% endblock extra_js %}

qa/templates/qa/profile.html
{% extends 'qa/base.html' %}
{% load django_markdown %}

{% block content %}
<h2 class="pull-right">Points: {{ user.points }}</h1>
<ul>
  <li><b>Website :</b> {{ user.website }} </li>
   <li><b>e-mail :</b> {{ user.user.email }} </li>
   <li><b>Date Joined :</b> {{ user.user.date_joined }} </li>
   <li><b>Last Login :</b> {{ user.user.last_login }} </li>
   <li><b>is Active :</b> {{ user.user.is_active }} </li>
<ul>

</div>
{% endblock content %}

qa/templates/qa/update_answer.html
{% extends 'qa/create_answer.html' %}

{% block action_url %}
{% url 'qa_update_answer' view.kwargs.answer_id %}
{% endblock action_url %}

qa/templates/qa/update_question.html
{% extends 'qa/create_question.html' %}

{% block action_url %}
{% url 'qa_update_question' view.kwargs.question_id %}
{% endblock action_url %}